version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: zabbix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: zabbixrootpass
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbixuser
      MYSQL_PASSWORD: zabbixpass
    networks:
      - zabbix-net
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3307:3306"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbixuser
      MYSQL_PASSWORD: zabbixpass
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_NAME: Zabbix-Server
    depends_on:
      - mysql
    networks:
      - zabbix-net
    volumes:
      - zabbix-data:/var/lib/zabbix
    restart: unless-stopped
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbixuser
      MYSQL_PASSWORD: zabbixpass
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Riga"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
    ports:
      - "8080:8080"
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: Zabbix-Agent-1
    networks:
      - zabbix-net
    restart: unless-stopped
    ports:
      - "10050:10050"
    expose:
      - "10050"

networks:
  zabbix-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  zabbix-data:
    driver: local  