services:
  zabbix:
    image: zabbix/zabbix-server-mysql:ubuntu-latest
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - db

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    environment:
      DB_SERVER_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      ZBX_SERVER_HOST: zabbix
    ports:
      - 8080:8080
    depends_on:
      - db
      - zabbix

  db:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  linux-server:
    build:
      context: ../linux-server
    container_name: linux-server

  python-app:
    build:
      context: ../python-app
    container_name: python-app
    ports:
      - "5000:5000"
    depends_on:
      - zabbix
      - zabbix-web
      - db
      - linux-server